name: Maven TestNG Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests with Maven (continue even if tests fail)
        run: mvn clean test -DsuiteXmlFile=testng.xml || true

      - name: Upload Test Reports and Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: |
            target/surefire-reports/
            logs/
            screenshots/

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

  allure-report:
    needs: build-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Allure Report with History
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      # ✅ Fix permissions + handle badge creation safely
      - name: Generate Allure Badges
        run: |
          sudo chmod -R 777 ${{ github.workspace }}
          cd ${{ github.workspace }}
          sudo apt-get update -y || true
          sudo apt-get install -y jq || true
          mkdir -p ${{ github.workspace }}/allure-report/badges
          if [ -f ${{ github.workspace }}/allure-report/widgets/summary.json ]; then
            summary="${{ github.workspace }}/allure-report/widgets/summary.json"
            total=$(jq '.statistic.total' "$summary")
            passed=$(jq '.statistic.passed' "$summary")
            failed=$(jq '.statistic.failed' "$summary")
            broken=$(jq '.statistic.broken' "$summary")
            skipped=$(jq '.statistic.skipped' "$summary")
            echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'><rect width='75' height='20' fill='#555'/><rect x='75' width='75' height='20' fill='#007ec6'/><text x='37.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>Tests</text><text x='112.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>${total}</text></svg>" > ${{ github.workspace }}/allure-report/badges/tests.svg
            echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'><rect width='75' height='20' fill='#555'/><rect x='75' width='75' height='20' fill='#4c1'/><text x='37.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>Passed</text><text x='112.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>${passed}</text></svg>" > ${{ github.workspace }}/allure-report/badges/passed.svg
            echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'><rect width='75' height='20' fill='#555'/><rect x='75' width='75' height='20' fill='#e05d44'/><text x='37.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>Failed</text><text x='112.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>${failed}</text></svg>" > ${{ github.workspace }}/allure-report/badges/failed.svg
            echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'><rect width='75' height='20' fill='#555'/><rect x='75' width='75' height='20' fill='#fe7d37'/><text x='37.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>Broken</text><text x='112.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>${broken}</text></svg>" > ${{ github.workspace }}/allure-report/badges/broken.svg
            echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'><rect width='75' height='20' fill='#555'/><rect x='75' width='75' height='20' fill='#dfb317'/><text x='37.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>Skipped</text><text x='112.5' y='14' fill='#fff' font-family='Verdana' font-size='11' text-anchor='middle'>${skipped}</text></svg>" > ${{ github.workspace }}/allure-report/badges/skipped.svg
          fi

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
